improve news script

diff --git a/bin/news b/bin/news
--- a/bin/news
+++ b/bin/news
@@ -3,8 +3,22 @@
 # streaming services channels and standalone vídeos. 
 # Using syncthing to sync this to my cellphone or other device to 
 # watch them.
-youtube_path=$1
-echo "$(date)" > $youtube_path/.lastrun
-cat $youtube_path/Channels > $youtube_path/Youtube
-cat $youtube_path/YoutubeFeed >> $youtube_path/Youtube
+
+youtube_path=${1%/}
+
+log=$youtube_path/.lastrun
+channels=$youtbe_path/Channels
+youtubefeed=$youtube_path/YoutubeFeed
+youtube=$youtube_path/Youtube
+
+if [ ! -d "$youtube_path" ]; then
+	echo "Error: Youtube path directory does not exist!"
+	exit 1
+fi
+
+echo "$(date)" > $log
+
+test -f $channels && cat $youtube_path/Channels > $youtube_path/Youtube
+test -f $youtubefeed && cat $youtube_path/YoutubeFeed >> $youtube_path/Youtube
+
 yt-dlp -a "$youtube_path/Youtube" --download-archive $youtube_path/YoutubeDL --dateafter 20221001 -o "$youtube_path/%(uploader)s/%(upload_date)s - %(title)s.%(ext)s" -f 'bestvideo[height<=480]+bestaudio/best[height<=480]' -i --force-ipv4 >> $youtube_path/.lastrun
